labels:
- name: 'Agent: DCA'
  color: E85AAD
  description: Group Instructions, Logic, Knowledge Sources, Data Sources and Tools
    together to apply to LLM's
  group: DCA →Schema
- name: 'Agent: EA'
  color: B33DC6
  description: Group Instructions, Logic, Knowledge Sources, Data Sources and Tools
    together to apply to LLM's
  group: 'Agent: EA →Agent: PA, Agent: DCA'
- name: 'Agent: PA'
  color: 6F42C1
  description: Group Instructions, Logic, Knowledge Sources, Data Sources and Tools
    together to apply to LLM's
- name: Car Charger
  color: 00C853
  description: Areas that Have processes associated with them
- name: Critical
  color: D0021B
  description: Categorise Issues
- name: EICR
  color: C62828
  description: Areas that Have processes associated with them
- name: Emergency Lighting
  color: C0CA33
  description: Areas that Have processes associated with them
- name: Fault Finding
  color: FB8C00
  description: Areas that Have processes associated with them
- name: Important
  color: FFB000
  description: Categorise Issues
- name: Install
  color: 0A84FF
  description: Areas that Have processes associated with them
- name: Non-Critical
  color: 00A650
  description: Categorise Issues
- name: 'Platform: ALM & Extensibility'
  color: 4B5563
  description: Management of the solution
  group: Solution Layers, Managed Properties, Custom Connectors
- name: 'Platform: Apps'
  color: 8B5CF6
  description: Data Input for the Dataverse Tables
  group: Platform Apps →Site Maps, Forms, Views, Dashboards
- name: 'Platform: Power Automate Flows'
  color: 00B5D1
  description: Transport system for Agent Data
  group: Power Automate Flows →Processes (Workflows), Plugins
- name: 'Platform: Security and Governance'
  color: 57606A
  description: Ensure Data Integrity
  group: Security Roles, Field Security Profiles
- name: 'Schema: Assembly Template'
  color: E36209
  description: Structured Data Source
  group: Assembly Template (Root) →ACI Materials (Child), ACI Task Units (Child))
    →Columns, Relationships, Business Rules, Keys, Indexes
- name: 'Schema: Bill of Materials (BOM)'
  color: B07219
  description: Structured Data Source
  group: 'BOM →Project: Materials →Columns: Relationships, Business Rules, Keys, Indexes'
- name: 'Schema: Circuit Instance'
  color: 8756FF
  description: Structured Data Source
  group: Circuits Instance (Root)) →Circuit End Point Distribution (Child)→Columns,
    Relationships, Business Rules, Keys, Indexes
- name: 'Schema: Material Task Units (MTU)'
  color: 0D9488
  description: Structured Data Source
  group: MTU) →Materials →Task Units →Variant Type Master (Reference) →Variant Rules
    (Child) →Columns, Relationships, Business Rules, Keys, Indexes
- name: 'Schema: Materials'
  color: 1F9E89
  description: Structured Data Source
  group: Materials (Reference) →Variant Type Master (Reference) →Variant Rules (Child)
    →UoM (Value Object) →Unit Conversion (Value Object) →Columns, Relationships, Business
    Rules, Keys, Indexes
- name: 'Schema: Price Policy'
  color: 2D6E2E
  description: Structured Data Source
  group: Price Policy (Root) →Labour Rates (Child) →Labour Roles (Reference) →Columns,
    Relationships, Business Rules, Keys, Indexes
- name: 'Schema: Project'
  color: 0B4F6C
  description: Structured Data Source
  group: Project (Root) →Project Documents (Child) →Columns, Relationships, Business
    Rules, Keys, Indexes
- name: 'Schema: Task Units'
  color: 2A7F62
  description: Structured Data Source
  group: Task Units (Reference) →Variant Type Master (Reference) →Variant Rules (Child)
    →Columns, Relationships, Business Rules, Keys, Indexes
- name: 'Schema: Variant Type Master'
  color: 10B981
  description: Structured Data Source
  group: 'Schema: Variant Type Master (Aggregate) →Variant Rules (Child)'
- name: 'Solution: OneDrive'
  color: 0078D4
  description: Container that groups files together on OneDrive
  group: 'Solution OneDrive → EA: PA: DCA'
- name: 'Solution: Power Platform'
  color: 1F6FEB
  description: Container that groups components together in Power Platform
  group: 'Solution Power Platform →Agent EA, Platform: PA Flows, Platform: Apps, Platform:
    Security and Governance'
- name: Testing
  color: 9C27B0
  description: Areas that Have processes associated with them
- name: Planning
  color: 4C1D95
  description: Planning phase labels for workflow generation
- name: 'agent: allowed'
  color: 059669
  description: Opt-in label to permit automated agent action on this issue
- name: 'agent: generated'
  color: 0369A1
  description: Applied by workflow to PRs created by automated agents
- name: 'agent: approved'  
  color: 16A34A
  description: Applied by human reviewer after inspecting agent-generated work
- name: 'agent: denied'
  color: DC2626
  description: Blocks automated agent action for this issue
- name: 'sub-issue'
  color: 7C3AED
  description: Indicates this is a sub-issue that should be linked to a parent
