name: Planning Phase (Parent Issue)
description: Create a parent planning issue that generates actions and creates branches
title: "[Planning] "
labels: ["Planning", "Agent: PA"]
projects: ["electricgltd/2"]
body:
  - type: markdown
    attributes:
      value: |
        ## Planning Phase Parent Issue
        
        This template creates a parent-level planning issue that triggers workflow actions
        and branch creation based on label combinations.
        
  - type: input
    id: planning-scope
    attributes:
      label: Planning Scope
      description: Brief description of what this planning phase covers
      placeholder: "e.g., EICR testing schedule for Q1 2024"
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level for this planning phase
      options:
        - Critical
        - Important
        - Non-Critical
    validations:
      required: true
      
  - type: dropdown
    id: agent
    attributes:
      label: Responsible Agent
      description: Select the primary agent responsible for this planning phase
      options:
        - "Agent: PA (Planning Agent)"
        - "Agent: EA (Electrical Agent)"
        - "Agent: DCA (Design & Costing Agent)"
    validations:
      required: true
      
  - type: checkboxes
    id: areas
    attributes:
      label: Areas Involved
      description: Select all areas that this planning phase relates to
      options:
        - label: Car Charger
          value: Car Charger
        - label: EICR
          value: EICR
        - label: Emergency Lighting
          value: Emergency Lighting
        - label: Fault Finding
          value: Fault Finding
        - label: Install
          value: Install
        - label: Testing
          value: Testing
          
  - type: input
    id: target-date
    attributes:
      label: Target Completion Date
      description: When should this planning phase be completed?
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
      
  - type: input
    id: estimate
    attributes:
      label: Estimated Hours
      description: How many hours is this planning phase expected to take?
      placeholder: "e.g., 8"
    validations:
      required: false
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be completed for this planning phase to be considered done?
      placeholder: |
        - [ ] Sub-issues created and assigned
        - [ ] Workflows configured and tested
        - [ ] Documentation updated
        - [ ] Stakeholders notified
    validations:
      required: true
      
  - type: textarea
    id: linked-documents
    attributes:
      label: Linked Documents (OneDrive)
      description: Links to OneDrive documents related to this planning phase
      placeholder: |
        - [Planning Document](OneDrive-link-here)
        - [Requirements Spec](OneDrive-link-here)
    validations:
      required: false
      
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional context or information for this planning phase
    validations:
      required: false