name: Validate Entity JSON

on:
  pull_request:
    paths:
      - 'schema_snapshots/**/*.json'
      - 'schema_snapshots/entity.schema.json'
  workflow_dispatch:

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Validate entity JSON files
        run: |
          echo "Validating schema_snapshots/*.entity.json against entity.schema.json"
          npx ajv validate -s schema_snapshots/entity.schema.json -d "schema_snapshots/*.entity.json" --strict=true
