name: Copilot • pickup issue comments

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: read

jobs:
  pickup:
    name: Pick up @copilot comments and create sub-tasks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (keeps workspace consistent)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run copilot pickup worker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          python scripts/issue_comment_autopick.py