name: DoctorGPhD Ruleset Validation

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate-doctorgphd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Validate DoctorGPhD ruleset
        run: python scripts/validate_doctorgphd.py