name: Enforce PR author (only @electricgltd)

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const allowed = ['electricgltd']; // <- your GitHub username
            const pr = context.payload.pull_request;
            const author = pr.user?.login || '';
            if (!allowed.includes(author)) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: This PR was opened by @\. Only @electricgltd is allowed to open PRs in this repo. Closing.
              });
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                state: 'closed'
              });
              core.setFailed('PR author not allowed. PR closed.');
            } else {
              core.notice('Author permitted.');
            }
