name: Power Platform CI/CD - Export Solution

on:
  workflow_dispatch:

jobs:
  export-solution:
    runs-on: windows-latest

    steps:
      # ✅ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Install Power Platform CLI
      - name: Install Power Platform CLI
        run: |
          dotnet tool install --global Microsoft.PowerPlatform.CLI.Tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # ✅ Authenticate using secrets
      - name: Authenticate with Power Platform
        run: |
          pac auth create --url ${{ secrets.DEV_ENV_URL }} `
                          --tenant ${{ secrets.TENANT_ID }} `
                          --applicationId ${{ secrets.CLIENT_ID }} `
                          --clientSecret ${{ secrets.CLIENT_SECRET }}
          pac auth select --index 1

      # ✅ Ensure solution folder exists
      - name: Create solution folder if missing
        run: |
          if (!(Test-Path "solution")) { mkdir solution }

      # ✅ Export the solution
      - name: Export Solution
        run: |
          pac solution export --name P100-Electrical-Agent-Suite `
                              --path solution/solution.zip `
                              --overwrite

      # ✅ Extract solution version from solution.xml
      - name: Get Solution Version
        id: get_version
        run: |
          Expand-Archive -Path solution/solution.zip -DestinationPath solution/unpacked
          [xml]$xml = Get-Content "solution/unpacked/solution.xml"
          $version = $xml.ImportExportXml.SolutionManifest.Version
          echo "version=$version" >> $env:GITHUB_OUTPUT

      # ✅ Upload artifact with version in name
      - name: Upload Exported Solution as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: P100-Electrical-Agent-Suite-${{ steps.get_version.outputs.version }}
          path: solution/solution.zip