name: PR metadata guard
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
permissions:
  pull-requests: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const errors = [];
            if (pr.head.ref === pr.base.ref || pr.head.ref.toLowerCase() === 'main') {
              errors.push(Use a feature branch (head: '\' → base: '\').);
            }
            const reviewersCount = (pr.requested_reviewers?.length || 0) + (pr.requested_teams?.length || 0);
            if (reviewersCount < 1) errors.push('Request at least one reviewer.');
            if (!pr.assignees || pr.assignees.length < 1) errors.push('Set an assignee.');
            if (!pr.milestone) errors.push('Select a milestone.');
            if (errors.length) {
              core.setFailed(errors.join('\n'));
            } else {
              core.notice('PR metadata looks good ✅');
            }
