name: MCP tests

on:
  push:
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-tests.yml'
  pull_request:
    paths:
      - 'mcp/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mcp/requirements.txt
      - name: Run tests
        # Ensure the repository root is on PYTHONPATH so `mcp` imports reliably
        env:
          PYTHONPATH: ${{ github.workspace }}
          # Allow the MCP dev server to accept the default 'dev-token' used by tests
          MCP_DEV_ALLOW_INSECURE: 'true'
        run: |
          pytest -q
