name: Power Platform ALM

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Power Platform CLI
        run: winget install Microsoft.PowerPlatformCLI --silent
      - name: Pack solution (unmanaged)
        run: |
          pac auth create --tenant ${{ secrets.PP_TENANT_ID }} --applicationId ${{ secrets.PP_APP_ID }} --clientSecret ${{ secrets.PP_CLIENT_SECRET }} --url ${{ secrets.PP_DEV_URL }}
          pac solution pack --zipfile _artifacts/P100_ElectricalAgentSuite_Unmanaged.zip --folder solutions/P100_ElectricalAgentSuite --managed false
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: solution-unmanaged
          path: _artifacts/P100_ElectricalAgentSuite_Unmanaged.zip

  import_to_test:
    needs: pack
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: solution-unmanaged
          path: _artifacts
      - name: Install Power Platform CLI
        run: winget install Microsoft.PowerPlatformCLI --silent
      - name: Import to TEST
        run: |
          pac auth create --tenant ${{ secrets.PP_TENANT_ID }} --applicationId ${{ secrets.PP_APP_ID }} --clientSecret ${{ secrets.PP_CLIENT_SECRET }} --url ${{ secrets.PP_TEST_URL }}
          pac solution import --path _artifacts/P100_ElectricalAgentSuite_Unmanaged.zip --publish-changes true --force-overwrite true
