name: Export Power Platform Solution

on:
  workflow_dispatch:

jobs:
  export-solution:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Install Power Platform CLI using official action
      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      # ✅ Verify PAC installation
      - name: Verify PAC installation
        run: pac --version
        shell: pwsh

      # ✅ Authenticate with Power Platform
      - name: Authenticate with Power Platform (pac)
        run: |
          pac auth create `
            --environment ${{ secrets.POWERPLATFORM_ENV }} `
            --tenant ${{ secrets.AZURE_TENANT_ID }} `
            --applicationId ${{ secrets.AZURE_CLIENT_ID }} `
            --clientSecret ${{ secrets.AZURE_CLIENT_SECRET }}
        shell: pwsh

      # ✅ Export solution
      - name: Export solution
        run: |
          pac solution export `
            --name P100-Electrical-Agent-Suite `
            --path ./exported-solution.zip `
            --managed false
        shell: pwsh

      # ✅ Extract version
      - name: Extract solution version
        id: get_version
        run: |
          Expand-Archive -Path ./exported-solution.zip -DestinationPath ./unpacked
          [xml]$solutionXml = Get-Content "./unpacked/solution.xml"
          $version = $solutionXml.ImportExportXml.SolutionManifest.Version
          echo "version=$version" >> $env:GITHUB_OUTPUT
        shell: pwsh

      # ✅ Upload artefact
      - name: Upload exported solution
        uses: actions/upload-artifact@v4
        with:
      
          name: P100-Electrical-Agent-Suite-${{ steps.get_version.outputs.version }}
          path: ./exported-solution.zip
