name: Power Platform Import Workflow

on:
  workflow_dispatch:

jobs:
  import-solution:
    runs-on: windows-latest

    steps:
      # ✅ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # ✅ Install Power Platform CLI
      - name: Install Power Platform CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # ✅ Authenticate with Service Principal
      - name: Authenticate with Power Platform
        run: |
          pac auth create `
            --tenant ${{ secrets.PPAC_TENANT_ID }} `
            --applicationId ${{ secrets.PPAC_CLIENT_ID }} `
            --clientSecret ${{ secrets.PPAC_CLIENT_SECRET }}

      # ✅ Download solution artifact
      - name: Download solution artifact
        uses: actions/download-artifact@v4
        with:
          name: solution-zip
          path: ./solution

      # ✅ Import solution into DEV
      - name: Import solution
        run: |
          pac solution import `
            --path ./solution/P100-Electrical-Agent-Suite.zip `
            --environment ${{ secrets.PPAC_ENVIRONMENT_URL_DEV }} `
            --overwrite `
            --publish-changes

      # ✅ Status check: Verify import completed successfully
      - name: Verify solution import status
        run: |
          echo "Checking solution status..."
          pac solution list --environment ${{ secrets.PPAC_ENVIRONMENT_URL_DEV }} | findstr "P100-Electrical-Agent-Suite"