name: export-and-commit
on:
  workflow_dispatch:

jobs:
  export-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Power Platform tools
        uses: microsoft/powerplatform-actions/actions-install@v1.9.0

      - name: WhoAmI (fail fast on creds)
        uses: microsoft/powerplatform-actions/who-am-i@v1.9.0
        with:
          environment-url: ${{ secrets.PP_ENVIRONMENT }}
          app-id:          ${{ secrets.PP_APP_ID }}
          tenant-id:       ${{ secrets.PP_TENANT_ID }}
          client-secret:   ${{ secrets.PP_CLIENT_SECRET }}

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1.9.0
        with:
          environment-url:     ${{ secrets.PP_ENVIRONMENT }}
          app-id:               ${{ secrets.PP_APP_ID }}
          tenant-id:            ${{ secrets.PP_TENANT_ID }}
          client-secret:        ${{ secrets.PP_CLIENT_SECRET }}
          solution-name:        ${{ secrets.PP_SOLUTION_NAME }}
          solution-output-file: 'out/${{ secrets.PP_SOLUTION_NAME }}.zip'
          working-directory:    'out'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exported-solution
          path: out/${{ secrets.PP_SOLUTION_NAME }}.zip