name: Power Platform Import to DEV

on:
  workflow_dispatch:

jobs:
  import-solution:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Power Platform CLI
        run: npm install -g pac

      - name: Authenticate
        run: |
          pac auth create --tenant ${{ secrets.PP_TENANT_ID }} `
                          --applicationId ${{ secrets.PP_CLIENT_ID }} `
                          --clientSecret ${{ secrets.PP_CLIENT_SECRET }} `
                          --environment ${{ secrets.PP_ENV_DEV_URL }}
        shell: pwsh

      - name: Pack solution
        run: |
          pac solution pack --zipFile ./Wip_Dataverse/P100-Electrical-Agent-Suite.zip `
                            --folder ./solutions/P100-Electrical-Agent-Suite `
                            --packagetype Unmanaged
        shell: pwsh

      - name: Validate zip exists
        run: |
          if (Test-Path "./Wip_Dataverse/P100-Electrical-Agent-Suite.zip") {
            Write-Host "✅ Zip file found."
            Get-Item "./Wip_Dataverse/P100-Electrical-Agent-Suite.zip" | Select-Object Name, Length
          } else {
            Write-Error "❌ Zip file not found. Pack step may have failed."
            exit 1
          }
        shell: pwsh

      - name: Import solution
        run: |
          pac solution import --path ./Wip_Dataverse/P100-Electrical-Agent-Suite.zip `
                              --async `
                              --max-async-wait 60 `
                              --overwrite `
                              --publish-changes
        shell: pwsh

      - name: Upload packed solution as artifact
        uses: actions/upload-artifact@v3
        with:
          name: P100-Electrical-Agent-Suite-Zip
          path: ./Wip_Dataverse/P100-Electrical-Agent-Suite.zip