name: Export Power Platform Solution (Artefact Only)

on:
  workflow_dispatch:

jobs:
  export-solution:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Authenticate and export using official Microsoft action
      - name: Authenticate with Power Platform
        uses: microsoft/powerplatform-actions@v1
        with:
          command: auth create
          args: >-
            --environment ${{ secrets.POWERPLATFORM_ENV }}
            --tenant ${{ secrets.AZURE_TENANT_ID }}
            --applicationId ${{ secrets.AZURE_CLIENT_ID }}
            --clientSecret ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Export solution
        uses: microsoft/powerplatform-actions@v1
        with:
          command: solution export
          args: >-
            --name P100-Electrical-Agent-Suite
            --path ./exported-solution.zip
            --managed false

      - name: Extract solution version
        id: get_version
        run: |
          Expand-Archive -Path ./exported-solution.zip -DestinationPath ./unpacked
          [xml]$solutionXml = Get-Content "./unpacked/solution.xml"
          $version = $solutionXml.ImportExportXml.SolutionManifest.Version
          echo "version=$version" >> $GITHUB_OUTPUT
        shell: pwsh

      - name: Upload exported solution
        uses: actions/upload-artifact@v4
        with:
          name: P100-Electrical-Agent-Suite-${{ steps.get_version.outputs.version }}
          path: ./exported-solution.zip