on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pack-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for solution sources
        id: check_sources
        run: |
          if [ -z "$(find solutions -name Solution.xml)" ]; then
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "found=true" >> $GITHUB_OUTPUT
          fi

      - name: Pack solution (DesignAndCosting)
        if: steps.check_sources.outputs.found == 'true'
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-folder: solutions/DesignAndCosting
          solution-file: out/DesignAndCosting.zip

      - name: Upload packed solution
        if: steps.check_sources.outputs.found == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: DesignAndCosting.zip
          path: out/DesignAndCosting.zip
