name: Export and Commit Power Platform Solution

on:
  workflow_dispatch:

jobs:
  export-and-commit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Power Platform CLI
        run: |
          Invoke-WebRequest -Uri https://aka.ms/PowerAppsCLIInstaller -OutFile pac.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/I pac.msi /quiet /qn /norestart'
          $env:PATH += ";C:\Program Files (x86)\Microsoft Power Platform CLI"
          pac --version
          echo "C:\Program Files (x86)\Microsoft Power Platform CLI" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Authenticate with Power Platform
        run: |
          pac auth create `
            --environment $env:POWERPLATFORM_ENV `
            --tenant $env:AZURE_TENANT_ID `
            --applicationId $env:AZURE_CLIENT_ID `
            --clientSecret $env:AZURE_CLIENT_SECRET
        shell: pwsh
        env:
          POWERPLATFORM_ENV: ${{ secrets.PPAC_ENVIRONMENT_URL_DEV }}
          AZURE_TENANT_ID: ${{ secrets.PPAC_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.PPAC_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.PPAC_CLIENT_SECRET }}

      - name: Export solution
        run: |
          pac solution export `
            --name P100-Electrical-Agent-Suite `
            --path ./exported-solution.zip `
            --managed false
        shell: pwsh

      - name: Extract version
        id: get_version
        run: |
          Expand-Archive -Path ./exported-solution.zip -DestinationPath ./unpacked
          [xml]$solutionXml = Get-Content "./unpacked/solution.xml"
          $version = $solutionXml.ImportExportXml.SolutionManifest.Version
          echo "version=$version" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Commit unpacked solution to repo
        run: |
          git config --global user.name "Gareth Youens"
          git config --global user.email "github-actions@github.com"
          mkdir -Force ./solutions/P100-Electrical-Agent-Suite
          Copy-Item -Path ./unpacked/* -Destination ./solutions/P100-Electrical-Agent-Suite -Recurse -Force
          git add solutions/P100-Electrical-Agent-Suite
          git commit -m "Exported solution version ${{ steps.get_version.outputs.version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh

      - name: Upload exported solution
        uses: actions/upload-artifact@v4
        with:
          name: P100-Electrical-Agent-Suite-${{ steps.get_version.outputs.version }}
          path: ./exported-solution.zip